[phases.setup]
# Update apt sources to include contrib and non-free repositories
cmds = [
  "echo 'deb http://deb.debian.org/debian bookworm main contrib non-free' > /etc/apt/sources.list",
  "echo 'deb http://deb.debian.org/debian-security bookworm-security main contrib non-free' >> /etc/apt/sources.list",
  "apt-get update"
]

# Install ARM64-compatible Chromium and dependencies
aptPkgs = [
  "chromium",
  "ca-certificates",
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcairo2",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxcomposite1",
  "libxcursor1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxi6",
  "libxrandr2",
  "libxrender1",
  "libxss1",
  "libxtst6",
  "xdg-utils",
  "curl",
  "wget"
]

# Set environment variables for Puppeteer
[phases.setup.env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"